### ISSUE TITLE
No package matching 'nginx-1.12.2' found available, installed or updated

### ISSUE THREAD

**Issue by WannaBeGeekster** [mbert/kubeadm2ha#1]
I am testing your scripts out and getting the following error:

TASK [nginx : Install nginx via package manager] ***********************************************************************************************************************************************************
fatal: [my-cluster-master-1]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'nginx-1.12.2' found available, installed or updated", "rc": 126, "results": ["No package matching 'nginx-1.12.2' found available, installed or updated"]}
fatal: [my-cluster-master-2]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'nginx-1.12.2' found available, installed or updated", "rc": 126, "results": ["No package matching 'nginx-1.12.2' found available, installed or updated"]}
fatal: [my-cluster-master-3]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'nginx-1.12.2' found available, installed or updated", "rc": 126, "results": ["No package matching 'nginx-1.12.2' found available, installed or updated"]}

**Comment by mbert** [comment]
@WannaBeGeekster it seems like on your system there is no package nginx-1.12.2 available. If your system is rpm-based (like mine) you may just try to install nginx by hand on one of your machines, look which version that is and override the variable holding the nginx version accordingly (assuming that you have created your own environment and created a group for your environment's hosts in your inventory file all you'd need to do is create a file group_vars/<group-name>.yaml and override the value there). If installing nginx via yum fails you'll probably need an additional repository for it. On EL systems nginx does not come with the distribution, you'll need EPEL for that.

If your distribution is not rpm-based there may be an issue with the way the version is coded into the package name when installing it in my ansible scripts (since I have no deb-based system at hand I could not verify this). In that case you may just edit the file roles/nginx/tasks/main.yaml and remove '-{{ NGINX_VERSION }}' from the package name. In that case you'll install just any nginx version that is available for your distribution and have no control over the version. 

Note that you are likely to stumble across the same problem in subsequent steps, the solution will be just about the same as here.

**Comment by WannaBeGeekster** [comment]
I was able to get around this error by adding the Nginx repository to the playbook.  I then also had to add the Kubernetes repository to the playbook as well.  Once I did that both applications installed correctly.
