### ISSUE TITLE
kube component can not do `Watch` when apiserver is set to VIP:PORT?

### ISSUE THREAD

**Issue by fengxsong** [mbert/kubeadm2ha#4]
hi (:
the default load balancing strategy of nginx is **rr**, so when a pod(sth like kube-proxy) do `Watch` action, it will print a lots of warning log message like

    W0301 02:10:52.929987       1 reflector.go:341] k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: watch of *core.Service ended with: very short watch: k8s.io/kubernetes/pkg/client/informers/informers_generated/internalversion/factory.go:85: Unexpected watch close - watch lasted less than a second and no items received

How to deal with this issue? or just ignore it?

**Comment by mbert** [comment]
The most obvious thing to try would be setting up load balancing with a strategy other than rr. As far as I understand, this is not supported by the free version NGINX (you'd have to upgrade to the expensive 'plus' edition). Hence something other than NGINX may be worth a try - at least in order to see whether the effect you describe disappears. 

I might take a look into this at some time, but this may take a while. If you have something in your sleeve I'd happily take a look at a PR :)

**Comment by mbert** [comment]
I've looked into this again today. When setting up nginx like this:

```
user  nginx;
worker_processes auto;

error_log  /var/log/nginx/error.log info;
pid        /var/run/nginx.pid;

load_module /usr/lib64/nginx/modules/ngx_stream_module.so;

events {
    worker_connections  1024;
}

stream {

    upstream apiserver {
        hash $remote_addr;
        server server1:6443 weight=5 max_fails=3 fail_timeout=30s;
        server server2:6443 weight=5 max_fails=3 fail_timeout=30s;
        server server3:6443 weight=5 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 8443;
        proxy_timeout 1s;
        proxy_connect_timeout 1s;
        proxy_pass apiserver;
    }

}
```

... I still run into the problem with "watch" commands. 

If you use `kubectl` from an external host, you may modify your _~/.kube/config_ file to use port 6443 instead of 8443, so that you circumvent the LB for your `kubectl` commands. That works just fine for me.

**Comment by mbert** [comment]
Closing this because there does not seem to be a tweak to get this working with _nginx_. Hence if one wants to use the 'watch' commands, then _nginx_ load balancing cannot be used.
